version: 2

registries:
  github-private:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.WOLF_GITBOT_PAT }}
    replaces-base: true

updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - github-private
    schedule:
      interval: "daily"
